dataset_name_cleaned: cleaned_dataset
dataset_name_customer: customer_agg
dataset_name_rfm: RFM

stage_inicial: inicial
stage_final: final

# =========================
# FEATURE ENGINEERING (Paso 3) - Ajustado a tus columnas reales
# =========================
feature_engineering:
  # --- Configuración de RFM ---
  rfm:
    # Si es null, se usa (max(TransactionDate) + 1 día)
    reference_date: null
    rfm_bins: 5
    columns:
      customer_id: CustomerID
      transaction_id: TransactionID
      transaction_date: TransactionDate
      amount: TransactionAmount (INR)

  # --- Segmentación basada en scores RFM ---
  rfm_segments:
    use_standard_segments: true

  # --- Features de valor de cliente (CLV simple, etc.) ---
  customer_value:
    annualization_factor: 12

  # --- Features específicas para detección de fraude ---
  fraud_detection:
    rapid_transaction_threshold_hours: 0.5
    high_value_threshold: null
    anomaly_zscore_threshold: 3
    columns:
      customer_id: CustomerID
      transaction_date: TransactionDate
      amount: TransactionAmount (INR)

# =========================
# DATA CLEANING / OUTLIERS
# =========================
data_cleaning:
  required_columns:
    - CustomerID
    - TransactionID
    - TransactionDate
    - Amount

  outlier_treatment:
    Amount:
      method: percentile     # iqr | percentile | zscore
      action: winsorize      # cap | remove | winsorize
      lower_percentile: 0.01
      upper_percentile: 0.99

  datetime:
    columns: [TransactionDate]
    infer_datetime_format: true
    utc: false

# ===========================================================
# Modelos de clasificación – rutas de guardado de modelos
# ===========================================================

# --- KNeighborsClassifier ---
knn_model_path: "data/06_models/clasificacion/knn_model.pkl"

# --- DecisionTreeClassifier ---
dt_model_path: "data/06_models/clasificacion/dt_model.pkl"

# --- RandomForestClassifier ---
rf_model_path: "data/06_models/clasificacion/rf_model.pkl"

# --- MLPClassifier ---
mlp_model_path: "data/06_models/clasificacion/mlp_model.pkl"

# --- XGBClassifier ---
xgb_model_path: "data/06_models/clasificacion/xgb_model.pkl"

# ===========================================================
# Modelos de regresión – rutas de guardado de modelos
# ===========================================================

# --- Linear Regression ---
linear_model_path: "data/06_models/regresion/linear_model.pkl"

# --- Ridge Regression ---
ridge_model_path: "data/06_models/regresion/ridge_model.pkl"

# --- Lasso Regression ---
lasso_model_path: "data/06_models/regresion/lasso_model.pkl"

# --- Random Forest Regressor ---
rf_regressor_model_path: "data/06_models/regresion/rf_regressor_model.pkl"

# --- XGBoost Regressor ---
xgb_regressor_model_path: "data/06_models/regresion/xgb_regressor_model.pkl"