stages:

  # =====================================================
  # 1️⃣ Data Engineering
  # =====================================================
  data_engineering:
    cmd: kedro run --pipeline=data_engineering
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/data_engineering
    outs:
      - data/02_intermediate:
          persist: true
      - data/03_primary:
          persist: true

  # =====================================================
  # 2️⃣ Feature Engineering
  # =====================================================
  feature_engineering:
    cmd: kedro run --pipeline=feature_engineering
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/feature_engineering
      - data/03_primary
    outs:
      - data/04_feature:
          persist: true

  # =====================================================
  # 3️⃣ Feature Selection / Model Input
  # =====================================================
  model_input:
    cmd: kedro run --pipeline=feature_selection
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/feature_selection
      - data/04_feature
    outs:
      - data/05_model_input/Features_training_v1.parquet:
          persist: true
      - data/05_model_input/Features_training_v2.parquet:
          persist: true

  # =====================================================
  # 4️⃣ Clasificación (RESULTADOS, NO MODELOS)
  # =====================================================
  classification_models:
    cmd: kedro run --pipeline=classification_models
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/classification_models
      - data/05_model_input/Features_training_v1.parquet
    outs:
      - data/07_model_output/clasificacion/knn_results.pkl:
          persist: true
      - data/07_model_output/clasificacion/dt_results.pkl:
          persist: true
      - data/07_model_output/clasificacion/rf_results.pkl:
          persist: true
      - data/07_model_output/clasificacion/mlp_results.pkl:
          persist: true
      - data/07_model_output/clasificacion/xgb_results.pkl:
          persist: true

  # =====================================================
  # 5️⃣ Regresión (RESULTADOS, NO MODELOS)
  # =====================================================
  regression_models:
    cmd: kedro run --pipeline=regression_models
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/regression_models
      - data/05_model_input/Features_training_v2.parquet
    outs:
      - data/07_model_output/regresion:
          persist: true

  # =====================================================
  # 6️⃣ Unsupervised Learning + XGB Final
  # =====================================================
  unsupervised_learning:
    cmd: kedro run --pipeline=unsupervised_learning
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/unsupervised_learning
      - data/05_model_input/Features_training_v1.parquet
      - data/05_model_input/Features_training_v2.parquet
      - data/07_model_output/regresion
    outs:
      - data/05_model_input/Features_clustering_v1.parquet:
          persist: true
      - data/06_models/clasificacion/xgb_final_model.pkl:
          persist: true
      - data/07_model_output/clustering:
          persist: true
      - data/07_model_output/clasificacion/xgb_final_metrics.json:
          persist: true
      - data/08_reporting/clustering:
          persist: true
      - data/08_reporting/clasificacion:
          persist: true

  # =====================================================
  # 7️⃣ Reporting
  # =====================================================
  reporting:
    cmd: kedro run --pipeline=reporting
    deps:
      - src/proyecto_ml_sebastiancarrera_kevinvivanco/pipelines/reporting
      - data/06_models/clasificacion
      - data/07_model_output/clasificacion
      - data/07_model_output/regresion
      - data/08_reporting/clasificacion
      - data/08_reporting/regresion
      - data/08_reporting/clustering
    outs:
      - data/08_reporting/dashboard/model_dashboard.html:
          persist: true